[package]
name = "dw"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
csv = "1.2"
encoding_rs = "0.8"
pcap = "2.2"

[dev-dependencies]
anyhow = "1.0.92"
criterion = "0.5"
struson = {version = "0.6", features = ["serde"]}



